env:
  browser: true
  jquery: true
extends:
  - standard
  - prettier
  - prettier/standard
  - plugin:vue/essential
parser: vue-eslint-parser
parserOptions:
  parser: babel-eslint
  sourceType: module
  allowImportExportEverywhere: false
plugins:
  - vue
globals:
  kintone: true
  Vue: true
  AWS: true
settings:
  import/resolver: webpack
rules:
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  prefer-const: error
  no-new: off
  #no-console:
  #  - error
  #  - allow:
  #    - warn
  #    - error
